export const PROFILE = { name:'Navneet Kumar', title:'Full Stack Developer', location:'Bangalore, Karnataka', email:'Navneetkumar1266@gmail.com', phone:'8340398051', github:'https://github.com/Navneet1266', linkedin:'https://www.linkedin.com/in/navneet-kumar-1266', summary:`Full‑stack developer specialized in building scalable web apps and delightful user interfaces. I work across React, Node.js, SQL, and modern tooling to ship fast, reliable products.` }
export const EDUCATION = [
  { school:'Kalinga Institute of Industrial Technology', degree:'B.Tech in Computer Science & Engineering', meta:'CGPA: 8.02', location:'Bhubaneswar, Odisha', period:'Aug 2021 – May 2025' },
  { school:'Vidya Sanskar School (CBSE)', degree:'Class XII', location:'Patna, Bihar', period:'2020' },
  { school:'St Karen’s High School (CBSE)', degree:'Class X', location:'Patna, Bihar', period:'2018' }]
export const EXPERIENCE = [
  { company:'Globiva', role:'Full Stack Developer', period:'Feb 2025 – Present', bullets:['Architected and delivered end‑to‑end web solutions using React, Node.js, JavaScript, SQL, and Bootstrap.','Built Report Incident, Holiday Master, Asset Management, and an advanced To‑Do List to streamline workflows.','Engineered scalable REST APIs and optimized queries for faster processing and reduced load times.']},
  { company:'Celebal Technologies', role:'Backend Intern', period:'Jun 2024 – Aug 2024', bullets:['Developed scalable server‑side applications with Node.js and Express.','Built and maintained REST APIs supporting dynamic web applications and real‑time systems.']}]
export const PROJECTS = [
  { name:'Yoom — Video Chat App', year:'2025', stack:['Next.js','TypeScript','Clerk','GetStream','Shadcn UI','Tailwind CSS'], description:'Secure, scalable video conferencing with auth, real‑time meetings, personal rooms, recording & playback.', link:'#', image:'/images/yoom.svg?v=2' },
  { name:'LLM Q&A Chatbot', year:'2025', stack:['Python','Flask','Sentence‑Transformers','ChromaDB','RAG'], description:'Document‑aware chatbot for Excel/PDF/CSV with embeddings, semantic+fuzzy matching, and PDF fallback.', link:'#', image:'/images/chatbot-v3.svg?v=3' }]
export const SKILLS = { frontend:['JavaScript','React','Redux','Redux Toolkit','Tailwind CSS','Bootstrap','D3.js'], backend:['Node.js','Express.js','MySQL','Socket.io','Cron Jobs'], languages:['JavaScript','Python','Java','SQL'], data:['NumPy','Pandas','Matplotlib','TensorFlow','Keras','OpenPyXL','PyMuPDF','PyPDF2','Regex','Sentence Transformers (MiniLM)','ChromaDB','Scikit‑learn']}
export const CERTIFICATIONS = [{ name:'HackerRank (Basic & Intermediate)', issuer:'HackerRank', date:'Aug 2023', location:'Bhubaneswar, Odisha' }]
